name: Hello Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@v4
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Build code
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint code
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo audit
        run: cargo audit
