name: Hello Rust CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Build code
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint code
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo audit
        run: cargo audit
